defmodule Haul.Repo.TenantMigrations.AddPaymentIntentIdToJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs, prefix: prefix()) do
      add :payment_intent_id, :text
    end
  end

  def down do
    alter table(:jobs, prefix: prefix()) do
      remove :payment_intent_id
    end
  end
end
