defmodule Haul.Repo.TenantMigrations.CreateOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:jobs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :customer_name, :text, null: false
      add :customer_phone, :text, null: false
      add :customer_email, :text
      add :address, :text, null: false
      add :item_description, :text, null: false
      add :preferred_dates, {:array, :date}, default: []
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "lead"
    end
  end

  def down do
    drop table(:jobs, prefix: prefix())
  end
end
