defmodule Haul.Repo.TenantMigrations.AddPhotoUrlsToJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs, prefix: prefix()) do
      add :photo_urls, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:jobs, prefix: prefix()) do
      remove :photo_urls
    end
  end
end
