defmodule Haul.Repo.TenantMigrations.CreateContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_configs_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:site_configs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:site_configs_versions, prefix: prefix()) do
      modify :version_source_id,
             references(:site_configs,
               column: :id,
               name: "site_configs_versions_version_source_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:site_configs, prefix: prefix()) do
      add :business_name, :text, null: false
      add :phone, :text, null: false
      add :email, :text
      add :tagline, :text
      add :service_area, :text
      add :address, :text
      add :coupon_text, :text, default: "10% OFF"
      add :meta_description, :text
      add :primary_color, :text, default: "#0f0f0f"
      add :logo_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:services_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:services, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:services_versions, prefix: prefix()) do
      modify :version_source_id,
             references(:services,
               column: :id,
               name: "services_versions_version_source_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:services, prefix: prefix()) do
      add :title, :text, null: false
      add :description, :text, null: false
      add :icon, :text, null: false
      add :sort_order, :bigint, null: false, default: 0
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:pages_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:pages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:pages_versions, prefix: prefix()) do
      modify :version_source_id,
             references(:pages,
               column: :id,
               name: "pages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:pages, prefix: prefix()) do
      add :slug, :text, null: false
      add :title, :text, null: false
      add :body, :text, null: false
      add :body_html, :text
      add :meta_description, :text
      add :published, :boolean, null: false, default: false
      add :published_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:pages, [:slug], name: "pages_unique_slug_index")

    create table(:gallery_items_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:gallery_items, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:gallery_items_versions, prefix: prefix()) do
      modify :version_source_id,
             references(:gallery_items,
               column: :id,
               name: "gallery_items_versions_version_source_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:gallery_items, prefix: prefix()) do
      add :before_image_url, :text, null: false
      add :after_image_url, :text, null: false
      add :caption, :text
      add :alt_text, :text
      add :sort_order, :bigint, null: false, default: 0
      add :featured, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:endorsements_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:endorsements, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:endorsements_versions, prefix: prefix()) do
      modify :version_source_id,
             references(:endorsements,
               column: :id,
               name: "endorsements_versions_version_source_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:endorsements, prefix: prefix()) do
      add :customer_name, :text, null: false
      add :quote_text, :text, null: false
      add :star_rating, :bigint
      add :source, :text
      add :date, :date
      add :featured, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :job_id,
          references(:jobs,
            column: :id,
            name: "endorsements_job_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:endorsements, "endorsements_job_id_fkey")

    alter table(:endorsements, prefix: prefix()) do
      remove :job_id
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :featured
      remove :date
      remove :source
      remove :star_rating
      remove :quote_text
      remove :customer_name
    end

    drop constraint(:endorsements_versions, "endorsements_versions_version_source_id_fkey")

    alter table(:endorsements_versions, prefix: prefix()) do
      modify :version_source_id, :uuid
    end

    drop table(:endorsements, prefix: prefix())

    drop table(:endorsements_versions, prefix: prefix())

    alter table(:gallery_items, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :featured
      remove :sort_order
      remove :alt_text
      remove :caption
      remove :after_image_url
      remove :before_image_url
    end

    drop constraint(:gallery_items_versions, "gallery_items_versions_version_source_id_fkey")

    alter table(:gallery_items_versions, prefix: prefix()) do
      modify :version_source_id, :uuid
    end

    drop table(:gallery_items, prefix: prefix())

    drop table(:gallery_items_versions, prefix: prefix())

    drop_if_exists unique_index(:pages, [:slug], name: "pages_unique_slug_index")

    alter table(:pages, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :published
      remove :meta_description
      remove :body_html
      remove :body
      remove :title
      remove :slug
    end

    drop constraint(:pages_versions, "pages_versions_version_source_id_fkey")

    alter table(:pages_versions, prefix: prefix()) do
      modify :version_source_id, :uuid
    end

    drop table(:pages, prefix: prefix())

    drop table(:pages_versions, prefix: prefix())

    alter table(:services, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :sort_order
      remove :icon
      remove :description
      remove :title
    end

    drop constraint(:services_versions, "services_versions_version_source_id_fkey")

    alter table(:services_versions, prefix: prefix()) do
      modify :version_source_id, :uuid
    end

    drop table(:services, prefix: prefix())

    drop table(:services_versions, prefix: prefix())

    alter table(:site_configs, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :logo_url
      remove :primary_color
      remove :meta_description
      remove :coupon_text
      remove :address
      remove :service_area
      remove :tagline
      remove :email
      remove :phone
      remove :business_name
    end

    drop constraint(:site_configs_versions, "site_configs_versions_version_source_id_fkey")

    alter table(:site_configs_versions, prefix: prefix()) do
      modify :version_source_id, :uuid
    end

    drop table(:site_configs, prefix: prefix())

    drop table(:site_configs_versions, prefix: prefix())
  end
end
