import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :haul, HaulWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :haul, HaulWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/healthz"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Production adapters — resolved at compile time via Application.compile_env.
# API keys and secrets are still loaded at runtime in config/runtime.exs.
config :haul, :ai_adapter, Haul.AI.Baml
config :haul, :chat_adapter, Haul.AI.Chat.Anthropic
config :haul, :payments_adapter, Haul.Payments.Stripe
config :haul, :billing_adapter, Haul.Billing.Stripe
config :haul, :sms_adapter, Haul.SMS.Twilio
config :haul, :places_adapter, Haul.Places.Google
config :haul, :cert_adapter, Haul.Domains.FlyApi

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
