defmodule Haul.Repo.Migrations.CreateAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :timezone, :text, null: false, default: "Etc/UTC"
      add :subscription_plan, :text, null: false, default: "free"
      add :stripe_customer_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:companies, [:slug], name: "companies_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:companies, [:slug], name: "companies_unique_slug_index")

    drop table(:companies)
  end
end
