defmodule Haul.Repo.Migrations.CreateAiCostEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_cost_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :conversation_id, :uuid
      add :function_name, :text, null: false
      add :model, :text, null: false
      add :input_tokens, :bigint, null: false
      add :output_tokens, :bigint, null: false
      add :estimated_cost_usd, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:ai_cost_entries, [:conversation_id])
    create index(:ai_cost_entries, [:inserted_at])
  end

  def down do
    drop table(:ai_cost_entries)
  end
end
