defmodule Haul.Repo.Migrations.AddDomainToCompanies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:companies) do
      add :domain, :text
    end

    create unique_index(:companies, [:domain], name: "companies_unique_domain_index")
  end

  def down do
    drop_if_exists unique_index(:companies, [:domain], name: "companies_unique_domain_index")

    alter table(:companies) do
      remove :domain
    end
  end
end
